import {describe,it,expect,vi,afterEach} from 'vitest';
import {demoSummary,fixtures,stages,request,setCSRF,ApiFailure} from './data';
afterEach(()=>vi.unstubAllGlobals());
describe('evidence workspace data boundaries',()=>{
 it('derives summary from fixture domain records, never fixed operating constants',()=>{const summary=demoSummary(fixtures);expect(summary.active_incidents).toBe(fixtures.filter(x=>x.incident.lifecycle_status==='active').length);expect(summary.cited_succeeded_runs).toBeLessThanOrEqual(summary.succeeded_runs);expect(demoSummary([]).mean_diagnosis_ms).toBeNull()});
 it('retry succeeded stage follows last persisted attempt and preserves failure history',()=>{const retry=fixtures.find(x=>x.fixture_id==='retry-succeeded')!;const stage=stages(retry.events).find(x=>x.stage==='retrieval')!;expect(stage.last?.kind).toBe('succeeded');expect(stage.rows.some(x=>x.kind==='failed')).toBe(true);expect(stage.retries).toBe(1)});
 it('does not invent a completed stage from a historical missing terminal record',()=>{const event=fixtures[0].events.find(e=>e.stage==='queue'&&e.kind==='started')!;const result=stages([event],'succeeded').find(s=>s.stage==='queue')!;expect(result.display).toBe('terminal_missing');expect(result.last?.kind).toBe('started');expect(result.last?.duration_ms).toBeNull()});
 it('keeps independently pending notification running after failed diagnosis',()=>{const event={...fixtures[0].events[0],stage:'notification' as const,kind:'started' as const};expect(stages([event],'failed','pending').find(s=>s.stage==='notification')?.display).toBe('started');expect(stages([event],'failed','sent').find(s=>s.stage==='notification')?.display).toBe('terminal_missing')});
 it('does not turn live failure into demo data',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:false,status:503,json:async()=>({error:'真实来源不可用'})}));await expect(request('/incidents')).rejects.toEqual(new ApiFailure('真实来源不可用',503))});
 it('forwards cancellation and cookie credentials; writes carry csrf',async()=>{const mock=vi.fn().mockResolvedValue({ok:true,json:async()=>({data:{},meta:{revision:1}})});vi.stubGlobal('fetch',mock);setCSRF('csrf-test');const controller=new AbortController();await request('/documents',controller.signal,{method:'POST',body:'{}'});expect(mock.mock.calls[0][1].signal).toBe(controller.signal);expect(mock.mock.calls[0][1].credentials).toBe('same-origin');expect(mock.mock.calls[0][1].headers.get('X-CSRF-Token')).toBe('csrf-test')});
});
