import {useEffect,useMemo,useState,useRef} from 'react';
import {ReactFlow,Background,Controls,MiniMap,Handle,Position,MarkerType,applyNodeChanges,useReactFlow,useNodesInitialized,type Node,type NodeProps} from '@xyflow/react';
import ELK from 'elkjs/lib/elk.bundled.js';
import type {GraphSnapshot,GraphNode,GraphEdge} from './domain';
import {label} from './data';
import {Icon} from './Icon';
import '@xyflow/react/dist/style.css';
const elk=new ELK();const cache=new Map<string,Node[]>();
const symbols:Record<string,string>={incident:'alert',alert:'alert',retrieval:'search',document_chunk:'knowledge',report:'document',service:'service',metric_observation:'metrics',hypothesis:'hypothesis'};
function FitGraph({onReady}:{onReady:(ready:boolean)=>void}){const initialized=useNodesInitialized();const flow=useReactFlow();const anchor=useRef<HTMLSpanElement>(null);useEffect(()=>{if(!initialized)return;const root=anchor.current?.closest('.graph-canvas');if(!root)return;let active=true;const fit=()=>{void document.fonts.ready.then(()=>{if(active)void flow.fitView({padding:.12,minZoom:.1,maxZoom:1}).then(()=>onReady(true))})};fit();const observer=new ResizeObserver(fit);observer.observe(root);return()=>{active=false;observer.disconnect()}},[initialized,flow.fitView,onReady]);return <span ref={anchor} hidden/>}
function EvidenceNode({data,selected}:NodeProps){const item=data.item as GraphNode;return <div className={'entity '+item.type+(selected?' chosen':'')}><Handle type="target" position={Position.Left}/><div className="entity-orb"><Icon name={symbols[item.type]}/></div><strong title={item.label}>{item.label}</strong><small title={item.subtitle}>{item.subtitle}</small>{item.verification==='unverified'&&<span className="muted">待核验</span>}<Handle type="source" position={Position.Right}/></div>}
const nodeTypes={evidence:EvidenceNode};
export function Graph({graph,selected,onSelect,kind='evidence'}:{kind?:'evidence'|'topology';graph:GraphSnapshot;selected:string|null;onSelect:(item:GraphNode|GraphEdge|null)=>void}){
 const [nodes,setNodes]=useState<Node[]>([]);const [layoutError,setLayoutError]=useState('');const [ready,setReady]=useState(false);const [fitted,setFitted]=useState(false);const [relation,setRelation]=useState('all');const [neighborhood,setNeighborhood]=useState(false);const [pathOnly,setPathOnly]=useState(false);const [list,setList]=useState(()=>matchMedia('(max-width:767px)').matches);
 const key=JSON.stringify([graph.id,graph.nodes,graph.edges]);
 useEffect(()=>{let active=true;setReady(false);setFitted(false);const run=async()=>{let result=cache.get(key);if(!result){const layoutStarted=performance.now();const layout=await elk.layout({id:'root',layoutOptions:{'elk.algorithm':'layered','elk.direction':'RIGHT','elk.layered.spacing.nodeNodeBetweenLayers':'20','elk.spacing.nodeNode':'30'},children:graph.nodes.map(n=>({id:n.id,width:160,height:165})),edges:graph.edges.map(e=>({id:e.id,sources:[e.source],targets:[e.target]}))});performance.measure('graph-layout-'+graph.id,{start:layoutStarted,end:performance.now()});result=graph.nodes.map(n=>({id:n.id,type:'evidence',position:{x:layout.children?.find(c=>c.id===n.id)?.x||0,y:layout.children?.find(c=>c.id===n.id)?.y||0},data:{item:n},width:160,height:165,ariaLabel:n.label}));cache.set(key,result)}if(active){setNodes(result);setReady(true)}};void run().catch(error=>{if(active){setLayoutError(error.message||'布局不可用');setList(true);setReady(true)}});return()=>{active=false}},[key]);
 const neighborIds=new Set([selected,...graph.edges.filter(e=>e.source===selected||e.target===selected).flatMap(e=>[e.source,e.target])]);
 const edges=useMemo(()=>graph.edges.filter(e=>(!neighborhood||!selected||neighborIds.has(e.source)&&neighborIds.has(e.target))&&(relation==='all'||e.relation===relation)&&(!pathOnly||!selected||e.source===selected||e.target===selected||e.id===selected)).map(e=>({id:e.id,source:e.source,target:e.target,label:label(e.relation),selected:selected===e.id,markerEnd:{type:MarkerType.ArrowClosed},style:{stroke:e.basis==='inferred'?'#f5cd63':'#63b3d5',strokeDasharray:e.basis==='inferred'?'6 5':undefined,strokeWidth:2,opacity:selected&&selected!==e.id&&selected!==e.source&&selected!==e.target ? .6 : 1},labelStyle:{fill:'#b6cee8',fontSize:12},labelBgStyle:{fill:'#091521'},ariaLabel:label(e.relation)})),[graph.edges,relation,pathOnly,selected,neighborhood]);
 return <>{layoutError&&<p role="alert" className="error">证据图布局不可用，显示完整可访问列表：{layoutError}</p>}<div className="graph-toolbar"><button onClick={()=>{setList(!list);if(list)setFitted(false)}}>{list?'证据图':'可访问证据列表'}</button><select aria-label="关系过滤" value={relation} onChange={e=>setRelation(e.target.value)}><option value="all">全部关系</option>{[...new Set(graph.edges.map(e=>e.relation))].map(x=><option key={x} value={x}>{label(x)}</option>)}</select><button disabled={!selected} onClick={()=>setNeighborhood(!neighborhood)}>{neighborhood?'全部节点':'一层邻域'}</button><button onClick={()=>{setNodes(cache.get(key)||[]);setNeighborhood(false);setPathOnly(false);setRelation('all')}}>重置布局</button><label><input type="checkbox" checked={pathOnly} onChange={e=>setPathOnly(e.target.checked)}/>仅当前路径</label></div><div className="graph-canvas" data-graph-layout-ready={ready&&(list||fitted||graph.nodes.length===0)}>
 {list?<div className="accessible-graph"><h3>实体与关系</h3>{graph.nodes.map(n=><button key={n.id} aria-pressed={selected===n.id} onClick={()=>onSelect(n)}>{n.label} · {n.subtitle}</button>)}{graph.edges.map(e=><button key={e.id} aria-pressed={selected===e.id} onClick={()=>onSelect(e)}>{graph.nodes.find(n=>n.id===e.source)?.label} → {label(e.relation)} → {graph.nodes.find(n=>n.id===e.target)?.label}</button>)}</div>:ready?<ReactFlow key={key} nodes={nodes.filter(n=>!neighborhood||!selected||neighborIds.has(n.id)).map(n=>({...n,selected:n.id===selected}))} edges={edges} onNodesChange={changes=>setNodes(old=>applyNodeChanges(changes,old))} nodeTypes={nodeTypes} nodesConnectable={false} edgesReconnectable={false} deleteKeyCode={null} onNodeClick={(_,n)=>onSelect(n.data.item as GraphNode)} onEdgeClick={(_,e)=>onSelect(graph.edges.find(x=>x.id===e.id)!)} onPaneClick={()=>onSelect(null)} fitView fitViewOptions={{padding:.12,minZoom:.1,maxZoom:1}} minZoom={.25} maxZoom={2} colorMode="dark"><FitGraph onReady={setFitted}/><Background gap={20} color="#1c3548"/><Controls showInteractive={false}/><MiniMap position="top-right" nodeColor="#317bb2" maskColor="#07111caa"/></ReactFlow>:<p>正在计算证据布局…</p>}</div><div className="graph-legend">{kind==='topology'?'服务 · 依赖　实线：declared / observed 有来源　潜在影响：inferred 待验证':'告警 / 事件 · 检索观测 · 知识片段 · 报告　实线：有记录　虚线：推断待核验'}{graph.truncated&&<span> · 已截断，另有 {graph.omitted_counts.nodes} 个节点 / {graph.omitted_counts.edges} 条关系</span>}</div></>;
}
