import {useState,useMemo} from 'react';
import {usePagedResource} from './useResource';
import {request,time,type Envelope} from './data';
import type {WorkspaceFixture} from './domain';
import {useModalKeyboard} from './useModalKeyboard';
interface Document {id:string;title:string;source_kind:string;active_version_id:string|null;deleted_at:string|null;index_status:string;environment?:string}
interface Version {id:string;document_id:string;content:string;content_sha256:string;created_at:string;status:string;index_status:string;chunks:unknown[]}
export function Knowledge({demo,refresh,zone}:{demo:WorkspaceFixture|undefined;refresh:number;zone?:string}){
 const demoDocs=useMemo(()=>demo?[...new Map(demo.evidence.filter(e=>e.document_id).map(e=>[e.document_id,{id:e.document_id!,title:String(e.metadata.title||e.document_id),source_kind:e.source_kind,active_version_id:e.version_id,deleted_at:null,index_status:'演示'}])).values()]:undefined,[demo]);
 const [tick,setTick]=useState(0);const docs=usePagedResource<Document>('/documents',demoDocs,refresh+tick);const [id,setId]=useState('');const selected=docs.value?.find(x=>x.id===id)||docs.value?.[0];
 const demoVersions=useMemo(()=>demo&&selected?[{id:selected.active_version_id!,document_id:selected.id,content:demo.evidence.filter(e=>e.document_id===selected.id).map(e=>e.snippet).join('\n\n'),content_sha256:'fixture：未提供hash',created_at:demo.meta.as_of,status:'active',index_status:'演示',chunks:[]}]:undefined,[demo,selected]);
 const versions=usePagedResource<Version>(selected?'/documents/'+encodeURIComponent(selected.id)+'/versions':null,demoVersions,refresh+tick);const [versionId,setVersionId]=useState('');const version=versions.value?.find(v=>v.id===versionId)||versions.value?.find(v=>v.id===selected?.active_version_id)||versions.value?.[0];
 const [editor,setEditor]=useState<'create'|'replace'|null>(null);const [title,setTitle]=useState('');const [environment,setEnvironment]=useState('unknown');const [content,setContent]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [remove,setRemove]=useState(false);const [query,setQuery]=useState('');
 useModalKeyboard(!!editor||remove,()=>{setEditor(null);setRemove(false)});
 async function save(){if(demo)return;setBusy(true);setError('');try{const result:Envelope<{document:Document;version:Version}>=await request(editor==='create'?'/documents':'/documents/'+encodeURIComponent(selected!.id),undefined,{method:editor==='create'?'POST':'PUT',headers:editor==='create'?{'Idempotency-Key':crypto.randomUUID()}:{'If-Match':selected!.active_version_id||''},body:JSON.stringify({title,content,source_kind:'upload',environment})});setId(result.data.document.id);setVersionId(result.data.version?.id||'');setEditor(null);setTick(x=>x+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function withdraw(){if(demo||!selected)return;setBusy(true);setError('');try{await request('/documents/'+encodeURIComponent(selected.id),undefined,{method:'DELETE',headers:{'If-Match':selected.active_version_id||''}});setRemove(false);setTick(x=>x+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="knowledge-grid"><aside className="panel"><div className="panel-head"><h2>全部文档 ({docs.value?.length??'—'})</h2><button disabled={!!demo} onClick={()=>{setEditor('create');setTitle('');setContent('');setEnvironment('unknown')}}>新建文档</button></div><label className="search"><input aria-label="搜索文档" placeholder="搜索文档标题…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{docs.error&&<p role="alert" className="error">{docs.error}</p>}{docs.value?.filter(d=>d.title.includes(query)).map(d=><button className={'doc-item'+(selected?.id===d.id?' selected':'')} key={d.id} onClick={()=>{setId(d.id);setVersionId('')}}><strong>▤　{d.title}</strong><span>{d.source_kind} · {d.deleted_at?'已撤下':'当前活动'}</span><small>{d.active_version_id} · {d.index_status}</small></button>)}{docs.hasMore&&<button onClick={docs.loadMore}>加载更多文档</button>}{!docs.value?.length&&<p className="empty">暂无文档，上传经审阅的运维手册。</p>}</aside><section className="panel document-content"><div className="panel-head"><h2>{selected?.title||'文档内容'}</h2><span>{selected?.deleted_at?'已撤下':'原始 Markdown'}</span></div><div className="tabs"><button className="active">文档内容</button><span>版本历史 ({versions.value?.length||0})</span></div>{version&&version.id!==selected?.active_version_id&&<p className="warning">历史引用版本，不参与当前默认检索</p>}{versions.error&&<p className="error">{versions.error}</p>}<pre className="markdown">{version?.content||'选择文档查看不可变版本与原文。'}</pre></section><aside className="panel inspector-body"><div className="panel-head"><h2>文档信息</h2></div><div className="action-row"><button disabled={!selected||!!demo||!!selected.deleted_at} onClick={()=>{setEditor('replace');setTitle(selected!.title);setContent(version?.content||'');setEnvironment(selected!.environment||'unknown')}}>替换版本</button><button className="danger" disabled={!selected||!!demo||!!selected.deleted_at} onClick={()=>setRemove(true)}>撤下</button></div>{demo&&<p className="warning">演示模式：管理操作不会发送到 live。</p>}{error&&<p role="alert" className="error">{error}</p>}<dl><dt>文档 ID</dt><dd>{selected?.id||'—'}</dd><dt>来源类型</dt><dd>{selected?.source_kind||'—'}（不代表人工审定）</dd><dt>适用环境</dt><dd>{selected?.environment||'unknown（适用环境未知）'}</dd><dt>活动版本</dt><dd>{selected?.active_version_id||'—'}</dd><dt>索引状态</dt><dd>{selected?.index_status||'—'}</dd><dt>内容 SHA256</dt><dd>{version?.content_sha256||'—'}</dd></dl><h3>版本历史</h3>{versions.value?.map(v=><button className="version-row" key={v.id} onClick={()=>setVersionId(v.id)} aria-pressed={v.id===version?.id}>{v.id===selected?.active_version_id?'当前版本':'历史版本'} · {v.id}<small>{time(v.created_at,zone)} · {v.index_status}</small></button>)}{versions.hasMore&&<button onClick={versions.loadMore}>加载更多版本</button>}</aside>
 {editor&&<div className="modal-backdrop"><form className="modal" role="dialog" aria-modal="true" aria-label="文档版本编辑" onSubmit={e=>{e.preventDefault();void save()}}><h2>{editor==='create'?'新建文档':'替换文档版本'}</h2><label>标题<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>适用环境<input required value={environment} onChange={e=>setEnvironment(e.target.value)} placeholder="unknown：适用环境未知"/></label><label>Markdown 原文<textarea required value={content} onChange={e=>setContent(e.target.value)} rows={12}/></label><p>激活成功前保留最后有效版本；并发修改会显示冲突。</p>{error&&<p className="error">{error}</p>}<div className="action-row"><button type="button" onClick={()=>setEditor(null)}>取消</button><button className="primary" disabled={busy}>保存并索引</button></div></form></div>}
 {remove&&<div className="modal-backdrop"><div className="modal" role="alertdialog" aria-modal="true" aria-labelledby="withdraw-title"><h2 id="withdraw-title">确认撤下 {selected?.title}？</h2><p>撤下后不再参与当前检索；历史报告引用和不可变快照仍保留。</p>{error&&<p className="error">{error}</p>}<div className="action-row"><button onClick={()=>setRemove(false)}>取消</button><button className="danger" disabled={busy} onClick={()=>void withdraw()}>确认撤下</button></div></div></div>}
 </div>
}
