import {useMemo,useState,useEffect,lazy,Suspense} from 'react';
import {useResource} from './useResource';
import type {Incident,WorkspaceFixture,GraphSnapshot,GraphNode,GraphEdge,EvidenceRecord} from './domain';
import {time,request} from './data';
const Graph=lazy(()=>import('./Graph').then(m=>({default:m.Graph})));
interface Metric {metric_id:string;unit:string;start:string;end:string;step:number;series:{labels:Record<string,string>;values:[number,number|null][]}[];source:string}
interface Topology {capability:string;nodes:{id:string;environment:string;namespace:string;service:string;source_ref:string}[];edges:{id:string;source:string;target:string;kind:string;source_ref:string;valid_from:string;valid_to:string|null}[];version:string;source_ref:string;as_of?:string;potential_impact?:{service_id:string;label:string;basis:string;source_refs:string[]}[]}
const templates=[['error_rate','错误率'],['request_rate','请求量'],['latency_p99','P99 延迟']];
function MetricPlot({id,name,endpoint,window,demo,incident,zone,highlight}:{id:string;name:string;endpoint:string|null;window:{start:string;end:string};demo?:WorkspaceFixture;incident?:Incident;zone?:string;highlight:boolean}){
 const [hidden,setHidden]=useState<number[]>([]);const [selection,setSelection]=useState<number|null>(null);
 const result=useResource<Metric>(endpoint?endpoint+'/metrics?'+new URLSearchParams({metric_id:id,start:window.start,end:window.end,step:'60'}):null,demo?{metric_id:id,unit:'—',...window,step:60,series:[],source:'演示 fixture 未提供时序数据'}:undefined);
 const points=result.value?.series.flatMap(s=>s.values.filter((v):v is [number,number]=>v[1]!==null))||[];const max=Math.max(.00001,...points.map(v=>v[1]));const start=Date.parse(result.value?.start||window.start)/1000;const end=Date.parse(result.value?.end||window.end)/1000;
 return <section id={'metric-'+id} className={'metric-strip'+(highlight?' metric-highlight':'')} data-metric-id={id} data-metric-ready={!result.loading}><div className="panel-head"><h2>{name} · 单位 {result.value?.unit||'—'}</h2><span>{id}</span></div>{result.error&&<p className="error" role="alert">{result.error}{result.stale?' · 上次成功 '+time(result.asOf,zone):''}</p>}
 {points.length?<><div className="series-legend">{result.value?.series.map((s,i)=><button key={i} aria-pressed={!hidden.includes(i)} onClick={()=>setHidden(h=>h.includes(i)?h.filter(x=>x!==i):[...h,i])}>{JSON.stringify(s.labels)}</button>)}</div><svg viewBox="0 0 1000 150" role="img" aria-label={name+'时序图'} onClick={event=>{const rect=event.currentTarget.getBoundingClientRect();setSelection(start+Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width))*(end-start))}}>{[0,1,2,3,4].map(x=><g key={x}><line x1="62" x2="975" y1={12+x*28} y2={12+x*28} stroke="#20354c"/><text x="4" y={16+x*28} fill="#aebfd3" fontSize="13">{(max*(4-x)/4).toPrecision(3)}</text></g>)}{result.value?.series.map((s,i)=>hidden.includes(i)?null:<path key={i} fill="none" stroke={['#ff646e','#ae8cf7','#45c5e5'][i%3]} strokeWidth="2" d={s.values.reduce((a,v,j)=>v[1]===null?a:a+((j===0||s.values[j-1][1]===null)?' M':' L')+(62+(v[0]-start)/(end-start)*913)+','+(124-v[1]/max*112),'')}/>)}{incident?.starts_at&&Date.parse(incident.starts_at)/1000>=start&&Date.parse(incident.starts_at)/1000<=end&&<line x1={62+(Date.parse(incident.starts_at)/1000-start)/(end-start)*913} x2={62+(Date.parse(incident.starts_at)/1000-start)/(end-start)*913} y1="8" y2="126" stroke="#60a5fa" strokeDasharray="5 5"/>}{selection!==null&&<line x1={62+(selection-start)/(end-start)*913} x2={62+(selection-start)/(end-start)*913} y1="8" y2="126" stroke="#eaf4ff" strokeDasharray="2 3"/>}</svg>{selection!==null&&<div className="sample-details">选中时间 {time(new Date(selection*1000).toISOString(),zone)}{result.value?.series.map((s,i)=>{const nearest=s.values.reduce<[number,number|null]|null>((best,item)=>!best||Math.abs(item[0]-selection)<Math.abs(best[0]-selection)?item:best,null);return <span key={i}> · {nearest?time(new Date(nearest[0]*1000).toISOString(),zone)+'：'+(nearest[1]===null?'缺失采样':nearest[1]+' '+result.value?.unit):'无采样'}</span>})}</div>}</>:<div className="empty metric-empty">{result.loading?'正在查询指标…':'暂无可绘制时序数据'}</div>}<p className="metric-source">来源：{result.value?.source||'未配置 / 不可用'}</p></section>
}
export function Metrics({incident,demo,zone,window}:{incident?:Incident;demo?:WorkspaceFixture;zone?:string;window:{start:string;end:string}}){
 const [metric,setMetric]=useState('error_rate');const [selection,setSelection]=useState<{scope:string;item:GraphNode|GraphEdge}|null>(null);const [sourceResult,setSourceResult]=useState<{scope:string;rows:EvidenceRecord[]}>({scope:'',rows:[]});const [topologySourceError,setTopologySourceError]=useState('');const endpoint=incident?'/incidents/'+encodeURIComponent(incident.id):null;
 const topology=useResource<Topology>(endpoint?endpoint+'/topology':null,demo?{capability:'not_configured',nodes:[],edges:[],version:'',source_ref:''}:undefined);
 const scope=(incident?.id||'')+'|'+(topology.value?.version||'');const selectedTopology=selection?.scope===scope?selection.item:null;const chooseTopology=(item:GraphNode|GraphEdge|null)=>setSelection(item?{scope,item}:null);
 useEffect(()=>{setSelection(null);setSourceResult({scope,rows:[]});setTopologySourceError('')},[scope]);
 const topologyGraph=useMemo<GraphSnapshot|null>(()=>topology.value?.nodes.length?{id:topology.value.version,incident_id:incident?.id||'',run_id:'',nodes:topology.value.nodes.map(n=>({id:n.id,type:'service',label:n.service,subtitle:n.environment+' / '+n.namespace,entity_ref:n.id,source_refs:[n.source_ref],verification:'not_applicable'})),edges:topology.value.edges.map(e=>({id:e.id,source:e.source,target:e.target,relation:'depends_on',basis:e.kind==='observed'?'observed':'declared',source_refs:[e.source_ref],recorded_at:e.valid_from,verification:'not_applicable'})),truncated:false,omitted_counts:{nodes:0,edges:0}}:null,[topology.value,incident?.id]);
 useEffect(()=>{setSourceResult({scope,rows:[]});setTopologySourceError('');if(!selectedTopology||demo)return;let active=true;const controller=new AbortController();Promise.all(selectedTopology.source_refs.map(ref=>request<EvidenceRecord>('/evidence/'+encodeURIComponent(ref),controller.signal))).then(rows=>{if(active)setSourceResult({scope,rows:rows.map(x=>x.data)})}).catch(e=>{if(active&&!controller.signal.aborted)setTopologySourceError(e.message)});return()=>{active=false;controller.abort()}},[selectedTopology,demo,scope]);
 return <><div className="metrics-context panel"><h2>{incident?.name||'请先选择事件'}</h2><span>{incident?.service||'—'} · 实时辅助观测，不属于历史报告证据</span><select aria-label="指标定位" value={metric} onChange={e=>{setMetric(e.target.value);document.getElementById('metric-'+e.target.value)?.scrollIntoView({block:'nearest'})}}>{templates.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></div><div className="metrics-grid"><section className="panel chart-panel metric-stack"><div className="panel-head"><h2>指标视图</h2><span>共享时间轴 · 独立单位 · 缺失采样断线</span></div>{templates.map(([id,name])=><MetricPlot key={id} id={id} name={name} endpoint={endpoint} demo={demo} incident={incident} zone={zone} window={window} highlight={metric===id}/>)}<p>{time(window.start,zone)} → {time(window.end,zone)}</p></section><aside className="panel"><div className="panel-head"><h2>关联事件</h2></div><div className="source"><h3>{incident?.name||'尚未选中事件'}</h3><p>{time(incident?.starts_at,zone)}</p><p>同一时间并不代表因果关系。</p></div><div className="source"><h3>声明式拓扑</h3>{topology.error?<p className="error">{topology.error}</p>:topology.value?.capability==='not_configured'?<p>未配置拓扑。服务依赖必须有可追溯来源。</p>:<p>版本 {topology.value?.version} · {topology.value?.source_ref}</p>}</div></aside></div><section className="panel query-details"><h2>查询详情</h2><p>受限模板：error_rate / request_rate / latency_p99 · step 60s · {time(window.start,zone)} → {time(window.end,zone)}</p><p>未存档的实时查询不自动添加证据节点；没有完整恢复记录，不计算 MTTR。</p></section>
 {topologyGraph&&<section className="panel topology-panel"><div className="panel-head"><h2>声明式服务拓扑</h2><span>版本 {topology.value?.version} · 实线：声明 / 观测来源，不代表故障</span></div><div className="topology-grid"><div className="topology-flow"><Suspense fallback={<p>加载服务拓扑…</p>}><Graph kind="topology" graph={topologyGraph} selected={selectedTopology?.id||null} onSelect={chooseTopology}/></Suspense></div><aside className="inspector-body"><h3>潜在影响</h3><p>反向依赖只表示潜在影响，未证明实际故障。</p>{topology.value?.potential_impact?.map(i=><button className="version-row" key={i.service_id} onClick={()=>chooseTopology({id:i.service_id,type:'service',label:i.label,subtitle:i.basis,entity_ref:i.service_id,source_refs:i.source_refs,verification:'unverified'})}>{i.label} · {i.basis}</button>)}{selectedTopology&&<><h3>{'label' in selectedTopology?selectedTopology.label:'依赖关系'}</h3><p>{'basis' in selectedTopology?selectedTopology.basis:'服务来源'}</p></>}{topologySourceError&&<p className="error">来源不可用：{topologySourceError}</p>}{(sourceResult.scope===scope?sourceResult.rows:[]).map(e=><div className="source" key={e.id}><p>{e.source_kind} · {e.source_ref}</p><p>{time(e.recorded_at,zone)}</p><pre>{e.snippet}</pre></div>)}</aside></div></section>}</>
}
