import {useEffect,useState} from 'react';
import type {Incident,DiagnosisRun,GraphSnapshot,GraphNode,GraphEdge,EvidenceRecord,RunEvent,WorkspaceFixture} from './domain';
import {label,duration,time,stages,request} from './data';
import {useResource,usePagedResource} from './useResource';
import {Graph} from './Graph';
export function Workspace({incidents,demo,onNavigate,zone,refresh,hasMore,onLoadMore,lifecycle,onLifecycleChange}:{lifecycle:string;onLifecycleChange:(value:string)=>void;hasMore:boolean;onLoadMore:()=>void;incidents:Incident[];demo:WorkspaceFixture|undefined;onNavigate:(id:string,run?:string)=>void;zone?:string;refresh:number}){
 const selectedId=new URLSearchParams(location.search).get('incident_id')||demo?.incident.id||incidents[0]?.id;const selectedRun=new URLSearchParams(location.search).get('run_id');
 const detail=useResource<{incident:Incident;runs:DiagnosisRun[]}>(selectedId?'/incidents/'+encodeURIComponent(selectedId):null,demo?{incident:demo.incident,runs:[demo.run]}:undefined,refresh);
 // Demo objects above are deliberately memoized by the parent fixture; avoid resource effect loops.
 const incident=detail.value?.incident;const runID=selectedRun||incident?.latest_run_id||detail.value?.runs[0]?.id;
 const run=useResource<DiagnosisRun>(runID?'/runs/'+encodeURIComponent(runID):null,demo?.run,refresh);
 const graph=useResource<GraphSnapshot>(incident&&runID?'/incidents/'+encodeURIComponent(incident.id)+'/graph?run_id='+encodeURIComponent(runID):null,demo?.graph,refresh);
 const events=usePagedResource<RunEvent>(runID?'/runs/'+encodeURIComponent(runID)+'/events':null,demo?.events,refresh,true);
 const [selected,setSelected]=useState<GraphNode|GraphEdge|null>(null);const [evidence,setEvidence]=useState<EvidenceRecord[]>([]);const [sourceError,setSourceError]=useState('');const [tab,setTab]=useState('graph');const [drawer,setDrawer]=useState(false);
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSelected(null);setDrawer(false)}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[]);
 useEffect(()=>{setSelected(null);setEvidence([]);setSourceError('')},[selectedId,runID]);
 useEffect(()=>{if(!selected){setEvidence([]);return}let active=true;const controller=new AbortController();setSourceError('');setEvidence([]);if(demo){setEvidence(demo.evidence.filter(e=>selected.source_refs.includes(e.id)));return}
 Promise.all(selected.source_refs.map(id=>request<EvidenceRecord>('/evidence/'+encodeURIComponent(id),controller.signal))).then(rows=>{if(active)setEvidence(rows.map(x=>x.data))}).catch(e=>{if(active&&!controller.signal.aborted)setSourceError(e.message)});return()=>{active=false;controller.abort()};},[selected,demo]);
 const choose=(item:GraphNode|GraphEdge|null)=>{setSelected(item);setDrawer(!!item)};const shown=incidents;
 return <div className={'workspace-grid'+(new URLSearchParams(location.search).has('incident_id')?' has-selection':'')}>
 <aside className="panel incident-rail"><div className="panel-head"><h2>事件列表 ({shown.length})</h2><select aria-label="生命周期筛选" value={lifecycle} onChange={e=>onLifecycleChange(e.target.value)}><option value="all">全部</option><option value="active">活跃</option><option value="resolved">已恢复</option><option value="unknown">未知</option></select></div><div className="incident-scroll">{shown.map((item,index)=><button className={'incident-item'+(item.id===selectedId?' selected':'')} key={item.id} aria-pressed={item.id===selectedId} onClick={()=>onNavigate(item.id)} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const next=shown[(index+(e.key==='ArrowDown'?1:-1)+shown.length)%shown.length];onNavigate(next.id);(e.currentTarget.parentElement?.children[(index+(e.key==='ArrowDown'?1:-1)+shown.length)%shown.length] as HTMLElement)?.focus()}}}><div><span className={'severity '+item.severity}>{item.severity}</span><span>{time(item.starts_at,zone)}</span><span className="badge">{label(item.lifecycle_status)}</span></div><strong>{item.name}</strong><small>{item.service} · {item.environment}</small></button>)}{!shown.length&&<p className="empty">暂无事件</p>}{hasMore&&<button onClick={onLoadMore}>加载更多事件</button>}</div></aside>
 <section className="panel investigation"><div className="investigation-head"><button className="mobile-back" onClick={()=>onNavigate('')}>返回事件列表</button>{incident?<><h2><span className={'severity '+incident.severity}>{incident.severity}</span> {incident.name}</h2><p>{incident.service} · {incident.environment} · {time(incident.starts_at,zone)} · {label(incident.lifecycle_status)}</p><div className="run-state">诊断：{run.value?label(run.value.status):'加载中'}　证据：{run.value?label(run.value.evidence_status):'—'}　通知：{run.value?label(run.value.notification_status):'—'}</div>{(detail.value?.runs.length||0)>1&&<label>运行 <select aria-label="选择诊断运行" value={runID||''} onChange={e=>onNavigate(incident.id,e.target.value)}>{detail.value?.runs.map(r=><option key={r.id} value={r.id}>{r.id} · {label(r.status)}</option>)}</select></label>}</>:<p>{detail.error||'请选择事件'}</p>}</div>
 <div className="tabs"><button className={tab==='graph'?'active':''} onClick={()=>setTab('graph')}>证据图谱</button><button className={tab==='report'?'active':''} onClick={()=>setTab('report')}>诊断报告</button><button className={tab==='events'?'active':''} onClick={()=>setTab('events')}>运行记录</button></div>
 {(detail.error||run.error||graph.error)&&<div role="alert" className="error">{detail.error||run.error||graph.error}{graph.stale&&' · 显示上次成功数据：'+time(graph.asOf,zone)}</div>}
 {tab==='graph'&&graph.value?<Graph graph={graph.value} selected={selected?.id||null} onSelect={choose}/>:tab==='report'?<div className="report"><h3>本轮诊断</h3><pre>{run.value?.report_text||'尚无报告'}</pre><p>引用数：{run.value?.citation_ids.length||0} · 模型自评：{run.value?.judge_score??'未评分'}（不是正确率）</p>{run.value?.error&&<p className="error">{run.value.error.message}</p>}</div>:tab==='events'?<div className="event-log">{events.value?.map(e=><p key={e.event_id}>#{e.sequence} {label(e.stage)} · {label(e.kind)} · attempt {e.attempt}/{e.stage_attempt} · {time(e.occurred_at,zone)} {e.error?.message}</p>)}{events.hasMore&&<button onClick={events.loadMore}>加载更多运行事件</button>}</div>:<p className="empty">{graph.loading?'加载证据…':'暂无证据图'}</p>}
 </section>
 <aside className={'panel inspector'+(drawer?' open':'')}><div className="panel-head"><h2>来源检查器</h2><button aria-label="关闭来源检查器" onClick={()=>{setDrawer(false);setSelected(null)}}>×</button></div>{selected?<div className="inspector-body"><h3>{'label' in selected?selected.label:label(selected.relation)}</h3><dl><dt>类型</dt><dd>{'type' in selected?selected.type:selected.basis+' · '+label(selected.relation)}</dd><dt>核验状态</dt><dd>{label(selected.verification)}</dd>{'recorded_at' in selected&&<><dt>关系记录</dt><dd>{time(selected.recorded_at,zone)}</dd></>}</dl>{sourceError&&<p role="alert" className="error">来源暂不可用：{sourceError}</p>}{evidence.map(e=><article className="source" key={e.id}><h3>{String(e.metadata?.title||e.kind)}</h3><dl><dt>来源</dt><dd>{e.source_kind}</dd><dt>定位</dt><dd>{e.source_ref}</dd><dt>记录时间</dt><dd>{time(e.recorded_at,zone)}</dd><dt>观测时间</dt><dd>{time(e.observed_at,zone)}</dd><dt>文档版本</dt><dd>{e.version_id||'—'}</dd><dt>片段</dt><dd>{e.chunk_id||'—'}</dd></dl>{e.metadata?.active_version===false&&<p className="warning">历史引用版本，不参与当前默认检索</p>}{e.metadata?.deleted_at!=null&&<p className="warning">文档已撤下，历史快照保留</p>}<pre>{e.snippet||'无片段'}</pre></article>)}</div>:<p className="empty">选择节点、关系或证据列表项，查看存档来源。</p>}</aside>
 <section className="panel timeline"><div className="panel-head"><h2>诊断执行时间线</h2><span>{duration(run.value?.duration_ms)} · {zone||Intl.DateTimeFormat().resolvedOptions().timeZone}</span></div><div className="stage-row">{stages(events.value||[],run.value?.status,run.value?.notification_status).map(s=><details className={'stage '+s.display} key={s.stage}><summary><strong>{label(s.stage)}</strong><span>{s.last?label(s.display):'暂无记录'}{s.retries>0?' · 重试'+s.retries+'次':''}</span><small>{duration(s.last?.duration_ms)}</small></summary>{s.rows.map(e=><p key={e.event_id}>{label(e.kind)} · {time(e.occurred_at,zone)} · attempt {e.attempt}/{e.stage_attempt} {e.error?.message}</p>)}</details>)}</div>{events.hasMore&&<button onClick={events.loadMore}>加载更多运行事件（历史未加载完全）</button>}{events.error&&<p role="alert" className="error">{events.error}</p>}</section>
 </div>
}
