import {test,expect} from '@playwright/test';
test('three metric units share request window, retain null gaps; declared topology has its own sourced legend',async({page})=>{
 const date=new Date().toISOString();const queries:{id:string;start:string|null;end:string|null;step:string|null}[]=[];
 await page.route('**/api/v1/**',async route=>{const url=new URL(route.request().url()),path=url.pathname;let data:unknown=[];
 if(path.endsWith('/incidents'))data=[{id:'i0',name:'受控指标事件',environment:'test',service:'svc',starts_at:date,lifecycle_status:'active',severity:'P2'}];
 else if(path.endsWith('/metrics')){const id=url.searchParams.get('metric_id')!;queries.push({id,start:url.searchParams.get('start'),end:url.searchParams.get('end'),step:url.searchParams.get('step')});const t=Date.parse(url.searchParams.get('start')!)/1000;data={metric_id:id,unit:{error_rate:'%',request_rate:'requests/s',latency_p99:'seconds'}[id],start:url.searchParams.get('start'),end:url.searchParams.get('end'),step:60,series:[{labels:{test_profile:'controlled'},values:[[t,5],[t+60,null],[t+120,8]]}],source:'controlled browser metrics fixture'}}
 else if(path.endsWith('/topology'))data={capability:'configured',version:'t1',source_ref:'evTopology',nodes:[{id:'test/ns/svc',environment:'test',namespace:'ns',service:'svc',source_ref:'evTopology'},{id:'test/ns/dependency',environment:'test',namespace:'ns',service:'dependency',source_ref:'evTopology'}],edges:[{id:'edge1',source:'test/ns/svc',target:'test/ns/dependency',kind:'declared',source_ref:'evTopology',valid_from:date,valid_to:null}],potential_impact:[{service_id:'test/ns/svc',label:'svc 的潜在影响',basis:'reverse-dependency',source_refs:['evTopology']}]};
 else if(path.endsWith('/evidence/evTopology'))data={id:'evTopology',kind:'topology',source_kind:'manual',source_ref:'controlled-topology-definition',recorded_at:date,snippet:'受控来源：显式声明依赖，不代表故障',metadata:{}};
 else if(path.endsWith('/auth/session'))data={csrf_token:'test',authenticated:true};else if(path.endsWith('/workspace/summary'))data={active_incidents:1,facets:{environments:['test'],services:['svc']}};else if(path.endsWith('/system/status'))data={capabilities:{},dependencies:{},config_fingerprint:'test'};
 await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data,meta:{revision:1,data_state:'fresh',as_of:date,mode:'live',next_cursor:null}})})});
 await page.goto('/metrics?incident_id=i0');await expect(page.locator('[data-metric-ready="true"]')).toHaveCount(3);await expect(page.getByRole('heading',{name:'错误率 · 单位 %'})).toBeVisible();await expect(page.getByRole('heading',{name:'请求量 · 单位 requests/s'})).toBeVisible();await expect(page.getByRole('heading',{name:'P99 延迟 · 单位 seconds'})).toBeVisible();expect(new Set(queries.map(q=>q.start+'|'+q.end+'|'+q.step)).size).toBe(1);expect(queries.map(q=>q.id).sort()).toEqual(['error_rate','latency_p99','request_rate']);
 for(const path of await page.locator('.metric-strip svg path').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('d')!)))expect((path.match(/M/g)||[]).length).toBe(2);
 await expect(page.locator('.topology-flow [data-graph-layout-ready="true"]')).toBeVisible();await expect(page.getByText('服务 · 依赖　实线：declared / observed 有来源　潜在影响：inferred 待验证',{exact:true})).toBeVisible();const style=await page.locator('.react-flow__edge-path').getAttribute('style');expect(style).not.toContain('stroke-dasharray');await page.getByRole('button',{name:'svc 的潜在影响 · reverse-dependency'}).click();await expect(page.getByText('controlled-topology-definition',{exact:false})).toBeVisible();await page.screenshot({path:'../../.omo/evidence/frontend-workspace/metrics-topology-controlled.png',fullPage:true});
});
test('topology selection and late source response cannot cross incident scopes',async({page})=>{
 const date=new Date().toISOString();await page.route('**/api/v1/**',async route=>{const url=new URL(route.request().url()),p=url.pathname;let data:unknown=[];if(p.endsWith('/incidents')){const svc=url.searchParams.get('service')||'A';data=[{id:svc,name:'事件'+svc,service:svc,environment:'test',starts_at:date}]}else if(p.endsWith('/workspace/summary'))data={facets:{environments:['test'],services:['A','B']}};else if(p.endsWith('/topology')){const id=p.includes('/A/')?'A':'B';data={capability:'configured',version:id,nodes:[{id,service:id,environment:'test',namespace:'ns',source_ref:'source'+id}],edges:[],potential_impact:[{service_id:id,label:'选择'+id,basis:'declared',source_refs:['source'+id]}]}}else if(p.includes('/evidence/')){const id=p.endsWith('sourceA')?'A':'B';if(id==='A')await new Promise(r=>setTimeout(r,1000));data={id:'source'+id,source_kind:'manual',source_ref:'scope'+id,snippet:'原文'+id,recorded_at:date}}else if(p.endsWith('/metrics'))data={series:[],source:'controlled'};else if(p.endsWith('/system/status'))data={capabilities:{},dependencies:{}};await route.fulfill({contentType:'application/json',body:JSON.stringify({data,meta:{revision:1,data_state:'fresh',as_of:date}})})});await page.goto('/workspace/metrics');await page.getByRole('button',{name:'选择A · declared'}).click();await page.getByLabel('服务筛选').selectOption('B');await expect(page.getByRole('button',{name:'选择B · declared'})).toBeVisible();await expect(page.locator('.topology-panel .inspector-body h3',{hasText:'选择A'})).toHaveCount(0);await page.getByRole('button',{name:'选择B · declared'}).click();await expect(page.getByText('原文B',{exact:true})).toBeVisible();await page.waitForTimeout(1200);await expect(page.getByText('原文A',{exact:true})).toHaveCount(0);await page.screenshot({path:'../../.omo/evidence/frontend-workspace/topology-scope-switch.png'});
});
