import {test,expect} from '@playwright/test';
test('all paginated resources expose records beyond default limits',async({page})=>{
 const date=new Date().toISOString();const incidents=Array.from({length:25},(_,i)=>({id:'i'+i,name:'事件'+(i+1),environment:'test',service:'svc'+i,severity:'P1',lifecycle_status:'active',starts_at:date,latest_run_id:'r0'}));
 const docs=Array.from({length:25},(_,i)=>({id:'d'+i,title:'文档'+(i+1),source_kind:'upload',environment:'test',active_version_id:'v25',deleted_at:null,index_status:'indexed'}));
 const versions=Array.from({length:25},(_,i)=>({id:'v'+(i+1),document_id:'d0',content:'原文版本'+(i+1),content_sha256:'hash'+i,created_at:date,status:'active',index_status:'indexed',chunks:[]}));
 const events=Array.from({length:120},(_,i)=>({event_id:'evt'+i,run_id:'r0',sequence:i+1,stage:'retrieval',stage_attempt:1,attempt:1,kind:i===119?'succeeded':'started',occurred_at:date,duration_ms:null,error:null,result_ref:null}));
 await page.route('**/api/v1/**',async route=>{const url=new URL(route.request().url());const p=url.pathname;let data:unknown=[];const meta:Record<string,unknown>={as_of:date,data_state:'fresh',mode:'live',revision:1,next_cursor:null,has_more:false};const offset=Number(url.searchParams.get('cursor')||0);const slice=(items:unknown[])=>{if(offset===0){meta.next_cursor='20';meta.has_more=true;return items.slice(0,20)}return items.slice(20)};
 if(p.endsWith('/auth/session'))data={csrf_token:'test',authenticated:true};else if(p.endsWith('/workspace/summary'))data={active_incidents:25,severity_distribution:{P1:25},facets:{environments:['test'],services:incidents.map(i=>i.service)}};
 else if(p.endsWith('/incidents'))data=slice(incidents);else if(p.endsWith('/incidents/i0'))data={incident:incidents[0],runs:[{id:'r0',status:'succeeded'}]};else if(p.endsWith('/runs/r0'))data={id:'r0',status:'succeeded',evidence_status:'has_citations',notification_status:'disabled',citation_ids:[],report_text:'安全报告',duration_ms:2};
 else if(p.endsWith('/graph'))data={id:'g',nodes:[],edges:[],truncated:false,omitted_counts:{nodes:0,edges:0}};
 else if(p.endsWith('/events')){const after=Number(url.searchParams.get('after_sequence')||0);data=events.filter(e=>e.sequence>after).slice(0,100);meta.has_more=after===0;meta.next_after_sequence=100}
 else if(p.endsWith('/documents'))data=slice(docs);else if(p.endsWith('/versions'))data=slice(versions);else if(p.endsWith('/system/status'))data={capabilities:{},dependencies:{},config_fingerprint:'test'};
 await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data,meta})})});
 await page.goto('/incidents?incident_id=i0');await page.getByRole('button',{name:'加载更多事件',exact:true}).click();await expect(page.getByRole('button',{name:/事件25/})).toBeVisible();await page.getByRole('button',{name:'加载更多运行事件（历史未加载完全）'}).click();await page.getByRole('button',{name:'运行记录',exact:true}).click();await expect(page.getByText('#120 检索',{exact:false})).toBeVisible();
 await page.goto('/knowledge');await page.getByRole('button',{name:'加载更多文档',exact:true}).click();await expect(page.getByRole('button',{name:/文档25/})).toBeVisible();await page.getByRole('button',{name:'加载更多版本',exact:true}).click();await expect(page.getByRole('button',{name:/当前版本 · v25/})).toBeVisible();docs[23].title='已刷新第二页文档24';docs.pop();await expect(page.getByRole('button',{name:/已刷新第二页文档24/})).toBeVisible({timeout:12000});await expect(page.getByRole('button',{name:/文档25/})).toHaveCount(0);
 await page.screenshot({path:'../../.omo/evidence/frontend-workspace/pagination-knowledge.png',fullPage:false});
});
test('live server search and receive-time scope are not re-filtered by stale startsAt',async({page})=>{
 const now=new Date().toISOString();let sawQuery=false;await page.route('**/api/v1/**',async route=>{const url=new URL(route.request().url());let data:unknown=[];if(url.pathname.endsWith('/incidents')){sawQuery ||= url.searchParams.get('query')==='cpu';data=[{id:'old-start',name:'CPUHigh',service:'node',environment:'test',severity:'P1',lifecycle_status:'active',starts_at:'2000-01-01T00:00:00Z',first_received_at:now,latest_run_id:null}]}else if(url.pathname.endsWith('/workspace/summary'))data={active_incidents:1,facets:{environments:['test'],services:['node']}};else if(url.pathname.endsWith('/auth/session'))data={csrf_token:'test',authenticated:true};else if(url.pathname.endsWith('/incidents/old-start'))data={incident:{id:'old-start',name:'CPUHigh',environment:'test',service:'node',starts_at:'2000-01-01T00:00:00Z'},runs:[]};else if(url.pathname.endsWith('/system/status'))data={capabilities:{},dependencies:{},config_fingerprint:'test'};await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data,meta:{as_of:now,revision:1,data_state:'fresh',mode:'live',next_cursor:null}})})});await page.goto('/incidents');await page.getByLabel('搜索事件或服务').fill('cpu');await expect(page.locator('.incident-item').filter({hasText:'CPUHigh'})).toBeVisible();expect(sawQuery).toBe(true);
});
test('lifecycle filter queries server and reaches resolved record beyond first twenty',async({page})=>{
 const date=new Date().toISOString();let serverFiltered=false;const resolved={id:'i21',name:'第二十一条已恢复',environment:'test',service:'svc',severity:'P2',lifecycle_status:'resolved',starts_at:date};await page.route('**/api/v1/**',async route=>{const url=new URL(route.request().url());let data:unknown=[];if(url.pathname.endsWith('/incidents')){serverFiltered=url.searchParams.get('status')==='resolved';data=serverFiltered?[resolved]:Array.from({length:20},(_,i)=>({...resolved,id:'i'+i,name:'活跃'+i,lifecycle_status:'active'}))}else if(/\/incidents\/i\d+$/.test(url.pathname))data={incident:url.pathname.endsWith('/i21')?resolved:{...resolved,id:'i0',name:'活跃0',lifecycle_status:'active'},runs:[]};else if(url.pathname.endsWith('/workspace/summary'))data={active_incidents:20,facets:{environments:['test'],services:['svc']}};else if(url.pathname.endsWith('/system/status'))data={capabilities:{},dependencies:{}};await route.fulfill({contentType:'application/json',body:JSON.stringify({data,meta:{revision:1,data_state:'fresh',as_of:date,has_more:!serverFiltered,next_cursor:serverFiltered?null:'20'}})})});await page.goto('/incidents');await page.getByLabel('生命周期筛选').selectOption('resolved');await expect(page.getByRole('button',{name:/第二十一条已恢复/})).toBeVisible();expect(serverFiltered).toBe(true);await page.screenshot({path:'../../.omo/evidence/frontend-workspace/lifecycle-server-filter.png'});
});
