import {test,expect} from '@playwright/test';
import {writeFileSync,mkdirSync} from 'node:fs';
import os from 'node:os';
for(const count of [60,300])test('controlled graph rendering measurement '+count,async({page})=>{
 const date=new Date().toISOString();const incident={id:'perf',name:'受控图性能场景',service:'controlled',environment:'test',severity:'P2',lifecycle_status:'active',starts_at:date,latest_run_id:'perf-run'};
 const nodes=Array.from({length:count},(_,i)=>({id:'n'+i,type:i===0?'incident':'document_chunk',label:i===count-1?'BrowserDiskFull_'+('1791303376733'.repeat(8)):'测试节点 '+i,subtitle:i===count-1?'ver_'+('ead30d2067c6882d31de7833e586d6bb'.repeat(4)):'受控合成场景',entity_ref:'ev'+i,source_refs:['ev'+i],verification:'unverified'}));
 const edges=Array.from({length:count*2},(_,i)=>({id:'e'+i,source:'n'+(i%count),target:'n'+((i%count+1+Math.floor(i/count))%count),relation:'cites',basis:'recorded',source_refs:['ev'+(i%count)],recorded_at:date,verification:'not_applicable'}));
 await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname;let data:unknown=[];
 if(path.endsWith('/incidents'))data=[incident];else if(path.endsWith('/incidents/perf'))data={incident,runs:[{id:'perf-run',status:'succeeded'}]};else if(path.endsWith('/runs/perf-run'))data={id:'perf-run',status:'succeeded',evidence_status:'has_citations',notification_status:'disabled',citation_ids:[],report_text:'受控性能场景'};
 else if(path.endsWith('/graph'))data={id:'perf-'+count,incident_id:'perf',run_id:'perf-run',nodes,edges,truncated:false,omitted_counts:{nodes:0,edges:0}};
 else if(path.includes('/evidence/'))data={id:'ev0',source_kind:'system',source_ref:'test:controlled-graph',recorded_at:date,snippet:'合成性能来源，仅测前端交互，不证明业务服务健康',metadata:{}};
 else if(path.endsWith('/workspace/summary'))data={active_incidents:1,facets:{environments:['test'],services:['controlled']}};else if(path.endsWith('/auth/session'))data={csrf_token:'test',authenticated:true};else if(path.endsWith('/system/status'))data={capabilities:{},dependencies:{},config_fingerprint:'perf'};
 await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data,meta:{revision:1,mode:'live',as_of:date,data_state:'fresh',next_cursor:null}})})});
 const start=Date.now();await page.goto('/incidents?incident_id=perf');await expect(page.locator('[data-graph-layout-ready="true"]')).toBeVisible({timeout:60000});const layoutMs=Date.now()-start;const clipped=await page.locator('.entity strong[title^=BrowserDiskFull_]').evaluate(element=>{const rect=element.getBoundingClientRect(),parent=element.parentElement!.getBoundingClientRect();const style=getComputedStyle(element);return {inside:rect.left>=parent.left-1&&rect.right<=parent.right+1,clamp:style.webkitLineClamp,wrap:style.overflowWrap,title:element.getAttribute('title'),text:element.textContent}});expect(clipped.inside).toBe(true);expect(clipped.clamp).toBe('2');expect(clipped.wrap).toBe('anywhere');expect(clipped.title).toBe(clipped.text);
 const selectionStart=Date.now();await page.getByRole('button',{name:'可访问证据列表'}).click();const inspectorInteractiveMs=await page.getByRole('button',{name:'测试节点 0 · 受控合成场景',exact:true}).evaluate(button=>new Promise<number>(resolve=>{const start=performance.now();const check=()=>{const inspector=document.querySelector('.inspector');if(inspector?.querySelector('h3')&&inspector.querySelector('button')){resolve(performance.now()-start);return}requestAnimationFrame(check)};(button as HTMLButtonElement).click();requestAnimationFrame(check)}));await expect(page.getByText('test:controlled-graph',{exact:true})).toBeVisible();const selectionMs=Date.now()-selectionStart;
 mkdirSync('../../.omo/evidence/frontend-workspace',{recursive:true});writeFileSync('../../.omo/evidence/frontend-workspace/performance-'+count+'.json',JSON.stringify({profile:'controlled synthetic frontend measurement; not production dependency validation',browser:page.context().browser()?.version(),host:{platform:os.platform(),architecture:os.arch(),cpu:os.cpus()[0]?.model,cpu_count:os.cpus().length,memory_bytes:os.totalmem()},concurrent_host_load:'See parent verification record; shared host may run Go race and Docker build',viewport:[1586,992],nodes:count,edges:edges.length,initial_load_and_layout_ms:layoutMs,accessible_selection_and_source_ms:selectionMs,node_selection_to_inspector_interactive_ms:inspectorInteractiveMs,inspector_measurement:"browser performance.now DOM click to inspector heading and close control, excludes source HTTP/list toggle",pure_elk_layout_ms:await page.evaluate((id)=>performance.getEntriesByName('graph-layout-'+id).at(-1)?.duration??null,'perf-'+count),browser_heap:await page.evaluate(()=>{const memory=(performance as unknown as {memory?:{usedJSHeapSize:number;totalJSHeapSize:number;jsHeapSizeLimit:number}}).memory;return memory?{used_js_heap_bytes:memory.usedJSHeapSize,total_js_heap_bytes:memory.totalJSHeapSize,heap_limit_bytes:memory.jsHeapSizeLimit,precision:'Chromium performance.memory estimate'}:{unsupported:true}})},null,2));
});
