import {test,expect} from '@playwright/test';
const pages=['dashboard','incidents','evidence','metrics','knowledge','evaluations','settings'];
for(const page of pages)test('demo page '+page,async({page:browser})=>{await browser.goto('/'+page+'?mode=demo');await expect(browser.getByText('演示数据',{exact:true}).first()).toBeVisible();await expect(browser.locator('h1')).toBeVisible();await expect(browser.locator('body')).not.toContainText('置信度0.72');if(page==='incidents'||page==='evidence'){await expect(browser.locator('[data-graph-layout-ready="true"]')).toBeVisible();await browser.getByRole('button',{name:'可访问证据列表'}).click();await browser.getByRole('button',{name:'检查范围 · Runbook v3 · chunk 1'}).click();await expect(browser.getByText('document:doc_demo_payment@version_demo_v3#chunk_demo_v3_01')).toBeVisible();await browser.getByRole('button',{name:'证据图',exact:true}).click();await expect(browser.locator('[data-graph-layout-ready="true"]')).toBeVisible()}if(page==='metrics'){await browser.locator('.metrics-context').waitFor();await browser.getByText('暂无可绘制时序数据',{exact:true}).first().waitFor();await expect(browser.locator('[data-metric-ready="true"]')).toHaveCount(3)}if(page==='knowledge')await browser.locator('.document-content h2').filter({hasText:'支付服务'}).waitFor();if(page==='settings')await browser.locator('.settings-grid>aside:last-child .panel:first-child pre').filter({hasText:'workspace'}).waitFor();await browser.evaluate(()=>document.fonts.ready);await browser.screenshot({path:'../../.omo/evidence/frontend-workspace/'+page+'-1586.png',fullPage:false})});
test('live failure remains visible without fixture substitution',async({page})=>{await page.route('**/api/v1/**',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'验证：真实接口不可用'})}));await page.goto('/incidents');await expect(page.getByText('接口不可用',{exact:true})).toBeVisible();await expect(page.getByText('支付服务5xx错误率上升',{exact:true})).toHaveCount(0);await expect(page.getByText('演示数据',{exact:true})).toHaveCount(0)});
for(const [width,height] of [[390,844],[768,1024],[1280,800],[1440,900],[1600,1000]])test('responsive '+width,async({page})=>{await page.setViewportSize({width,height});await page.goto('/incidents?mode=demo');if(width<768)await page.locator('.incident-item').first().click();await expect(page.locator('[data-graph-layout-ready="true"]')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await page.screenshot({path:'../../.omo/evidence/frontend-workspace/incidents-'+width+'.png',fullPage:true})});
test('authenticated version management sends csrf and optimistic version boundary',async({page})=>{
 let active='v1';let removed=false;const writes:{method:string;csrf:string;match:string}[]=[];
 await page.route('**/api/v1/**',async route=>{const r=route.request(),path=new URL(r.url()).pathname;let data:unknown=[];
 if(path.endsWith('/auth/session'))data={csrf_token:'test-csrf',authenticated:true};
 else if(path.endsWith('/system/status'))data={capabilities:{},dependencies:{},config_fingerprint:'test'};
 else if(path.endsWith('/workspace/summary'))data={active_incidents:0,no_evidence_incidents:0,succeeded_runs:0,cited_succeeded_runs:0,mean_diagnosis_ms:null,source_unavailable_incidents:0};
 else if(path.endsWith('/documents'))data=[{id:'d1',title:'测试文档',source_kind:'upload',active_version_id:active,deleted_at:removed?'2026-10-06T00:00:00Z':null,index_status:'indexed'}];
 else if(path.endsWith('/versions'))data=[{id:active,document_id:'d1',content:'安全文本 <script>alert(1)</script>',content_sha256:'test-hash',created_at:'2026-10-06T00:00:00Z',status:'active',index_status:'indexed',chunks:[]}];
 else if(path.endsWith('/documents/d1')){writes.push({method:r.method(),csrf:r.headers()['x-csrf-token'],match:r.headers()['if-match']});if(r.method()==='PUT')active='v2';if(r.method()==='DELETE')removed=true;data={document:{id:'d1'},version:{id:active}}};
 await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data,meta:{as_of:'2026-10-06T00:00:00Z',revision:1,data_state:'fresh',mode:'live'}})})});
 await page.goto('/knowledge');await expect(page.getByRole('button',{name:'替换版本'})).toBeEnabled();await page.getByRole('button',{name:'替换版本'}).click();await page.getByLabel('Markdown 原文').fill('新版本');await page.getByRole('button',{name:'保存并索引'}).click();await expect(page.getByText('v2',{exact:true}).first()).toBeVisible();await page.getByRole('button',{name:'撤下',exact:true}).click();await page.getByRole('button',{name:'确认撤下'}).click();await expect(page.getByText('已撤下',{exact:true}).first()).toBeVisible();expect(writes).toEqual([{method:'PUT',csrf:'test-csrf',match:'v1'},{method:'DELETE',csrf:'test-csrf',match:'v2'}]);expect(await page.evaluate(()=>Object.keys(localStorage))).toEqual([]);
});
test('explicit fixture scenarios use selected snapshot, preserving no-evidence and retry semantics',async({page})=>{await page.goto('/incidents?mode=demo');await page.getByLabel('演示情景').selectOption('no-evidence');await expect(page.locator('.run-state')).toContainText('无证据');await page.getByLabel('演示情景').selectOption('source-unavailable');await expect(page.locator('.run-state')).toContainText('来源不可用');await page.getByLabel('演示情景').selectOption('retry-succeeded');await expect(page.locator('.stage').filter({hasText:'检索'}).locator('summary')).toContainText('成功');await expect(page.getByText('成功 · 重试1次')).toBeVisible()});
test('login modal traps keyboard focus and Escape closes; Inspector Escape clears selection',async({page})=>{
 await page.route('**/api/v1/**',r=>r.fulfill({status:503,contentType:'application/json',body:'{"error":"受控接口不可用"}'}));await page.goto('/incidents');await page.getByRole('button',{name:'会话',exact:true}).click();await expect(page.getByLabel('Console token')).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(page.getByRole('button',{name:'登录',exact:true})).toBeFocused();await page.keyboard.press('Tab');await expect(page.getByLabel('Console token')).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.goto('/incidents?mode=demo');await page.getByRole('button',{name:'可访问证据列表'}).click();const node=page.getByRole('button',{name:'检查范围 · Runbook v3 · chunk 1'});await node.click();await expect(node).toHaveAttribute('aria-pressed','true');await page.keyboard.press('Escape');await expect(node).toHaveAttribute('aria-pressed','false');await expect(page.getByText('document:doc_demo_payment@version_demo_v3#chunk_demo_v3_01')).toHaveCount(0);
});
